version: 0.2

env:
  variables:
    REACT_APP_API_BASE_URL: "https://my-backend-app-v7-env.eba-vffxtgtm.us-east-1.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building React app...
      - echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL"
      - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL npm run build

artifacts:
  files:
    - "**/*"
  base-directory: build
