version: 0.2

env:
  variables:
    #This is used to connect frontend to backend which is beyond the scope for this MP during beta testing
    REACT_APP_API_BASE_URL: "https://{beanstalk-backend}.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
